---
- name: Install common base packages (Debian)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: common_base_packages

- name: Install Debian-specific base packages (Debian)
  apt:
    name: "{{ item }}"
    state: present
  with_items: debian_base_packages
