---
- set_fact:
    is_satellite: "{{ rhn_server_hostname != 'subscription.rhn.redhat.com' }}"
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_redhat: "{{ ansible_os_family == 'RedHat' }}"
    is_freebsd: "{{ ansible_os_family == 'FreeBSD' }}"

- include: rhel.yml
  when: is_redhat

- include: debian.yml
  when: is_debian

- include: freebsd.yml
  when: is_freebsd
