---
- set_fact:
    is_satellite: "{{ rhn_server_hostname != 'subscription.rhn.redhat.com' }}"
    is_debian: "{{ ansible_os_family == 'Debian' }}"
    is_redhat: "{{ ansible_os_family == 'RedHat' }}"
    is_freebsd: "{{ ansible_os_family == 'FreeBSD' }}"

- include: rhel.yml
  when: is_redhat

- include: debian.yml
  when: is_debian

- include: freebsd.yml
  when: is_freebsd

- name: Check if pip is installed
  shell: which pip
  register: check_pip
  changed_when: no
  failed_when: no

- name: Install Python base packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_packages }}"
  when: check_pip.rc == 0
